### ISSUE TITLE
duplicate_timestamps not of package's namespace

### ISSUE THREAD

**Issue by felxcon** [Mayur1009/cleanTS#1]
Hi,
I tried to cleanTS myListOfDataframes (via making cleanTS() a particular function and lapply) when I came across that it had problem, in short terms, with timestamps. Following up on this I figured that, calling ...
#cleanTS::duplicate_timestamps()
would result in
#Error: 'duplicate_timestamps' is not an exported object from 'namespace:cleanTS'
Apparently the function is totally missing in the CRAN and github repository provided for RStudio!!!
In the meantime I will figure a workaround but it would be so nice to get that function available und working.
Thank you for looking in to it and fixing it, hopefully :)
Cheers
PS: I partially had DFs with half-hourly data which apparantly discovered this missing function since my code works all just fine on non-duplicate timestamp dataframe ! ;)

**Comment by Mayur1009** [comment]
Hello, 
Sorry for the really late reply. 
The `duplicate_timestamps()` function is a helper function not meant to be used directly and thus not exported by the library.
